### ISSUE TITLE
onnxruntime/cublas error

### ISSUE THREAD

**Issue by nicholas-miles** [Nick088Official/FaceFusion-Online-Ports#10]
After install (on an A100 colab instance), the RunUI step shows the following error:

`[E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory`

**Comment by nicholas-miles** [comment]
Fixed by running `!apt-get update` before re running `!apt-get install nvidia-cuda-toolkit`

**Comment by Nick088Official** [comment]
That's kinda weird, I don't pay for colab but on the Free T4 i don't get any issues even if i dont have `!apt-get update`
