### ISSUE TITLE
From 21 April updating Run Ui not work Anymore.

### ISSUE THREAD

**Issue by MarcusWebby** [Nick088Official/FaceFusion-Online-Ports#2]
Helle Friend, from the last updating of April 21 when i run Run Ui on your repository it download some files but at end write in red fonts this error:
2024-04-21 14:20:38.871015917 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

2024-04-21 14:20:39.133831290 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

2024-04-21 14:20:39.548109497 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

2024-04-21 14:20:39.895284337 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

2024-04-21 14:20:39.902515579 [E:onnxruntime:Default, provider_bridge_ort.cc:1548 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1209 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory

Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://3b5a2c73944b927b9c.gradio.live/

WHAT TO DO for run correctly????

**Comment by Nick088Official** [comment]
Hello, sorry didn't see this issue before, which port are you using? the hugging face one? because currently the space has issues when duplicating the space with gpu (so uses the cpu instead), if you are using other ports, its prolly bc you werent using the free gpu and putted cuda enabled in the execution providers

**Comment by Nick088Official** [comment]
Im gonna close this for now has its been more than 2 weeks, i think the problem is fixed as i said in the previous comment a i didnt get other reports of this and neither had it.
